- name: Barbell
  default_weight: 45.0
  track_weight: true
  has_resistance_levels: false
- name: Dumbbell
  default_weight: 0.0
  track_weight: true
  has_resistance_levels: false
- name: Machine
  default_weight: 0.0
  track_weight: true
  has_resistance_levels: false
- name: Cable
  default_weight: 0.0
  track_weight: true
  has_resistance_levels: false
- name: Bodyweight
  default_weight: 0.0
  track_weight: false
  has_resistance_levels: false
